// <auto-generated />
namespace HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class events4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(events4));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031644381_events4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
